name: AI Contribution

on:
  schedule:
    # Run every 3 hours
    - cron: "30 */3 * * *"
  workflow_dispatch:  # allow manual run

jobs:
  ai_contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI contribution script
        run: |
          python scripts/update.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet || (git commit -m "AI contribution update" && git push)

