from jobs_scraper import run as run_jobs
from ml_scraper import run as run_ml
from ai_contribution import run as run_contrib

def safe_run(func, name):
    try:
        print(f"[INFO] Running {name}...")
        func()
        print(f"[INFO] {name} completed successfully.")
    except Exception as e:
        print(f"[ERROR] {name} failed: {e}")

if __name__ == "__main__":
    safe_run(run_jobs, "Jobs Scraper")
    safe_run(run_ml, "ML Scraper")
    safe_run(run_contrib, "AI Contributions")




