name: Auto Update AI Tracker

on:
  schedule:
    - cron: "0 5/3 * * *"   # Start at 10:30 AM IST, repeat every 3 hours
  workflow_dispatch:        # Allow manual run anytime


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (light)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: |
          python scripts/update.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet || (git commit -m "auto: refresh data" && git push)
