name: Daily Update

on:
  schedule:
    - cron: "30 10-23/3 * * *"   # Every 3 hours starting 10:30
  workflow_dispatch:
    inputs:
      script:
        description: "Daily update script to run"
        required: false
        default: "scripts/daily_update.py"

permissions:
  contents: write

jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas numpy matplotlib

      - name: Run Daily Update Script
        run: python ${{ github.event.inputs.script || 'scripts/daily_update.py' }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Daily update at $(date)" || echo "No changes to commit"
          git push


