name: Weekly ML Training

on:
  schedule:
    - cron: "0 6 * * 0"   # Runs every Sunday at 06:00 UTC
  workflow_dispatch:
    inputs:
      script:
        description: "ML training script to run"
        required: false
        default: "scripts/train_ml.py"

permissions:
  contents: write

jobs:
  weekly-ml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"
          pip install scikit-learn pandas numpy matplotlib seaborn

      - name: Run ML Training Script
        run: python ${{ github.event.inputs.script || 'scripts/train_ml.py' }}

      - name: Commit and Push Model/Results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Weekly ML training update at $(date)" || echo "No changes to commit"
          git push


